module.exports = {
  config: {
    scrollback: 100000,
    fontSize: 14,
    fontFamily: "Fira Code",
    cursorColor: "#F8F8F0",
    cursorShape: "UNDERLINE",
    foregroundColor: "#F8F8F2",
    backgroundColor: "#5A5475",
    css: "",
    termCSS: "",
    showHamburgerMenu: "",
    showWindowControls: "",
    padding: "12px 14px",
    colors: {
      black: "#000000",
      red: "#ff5c57",
      green: "#5af78e",
      yellow: "#f3f99d",
      blue: "#57c7ff",
      magenta: "#ff6ac1",
      cyan: "#9aedfe",
      white: "#f1f1f0",
    },
    shell: "/bin/zsh",
    shellArgs: ["--login"],
    env: {},
    bell: "FALSE",
    copyOnSelect: false,
  },
  plugins: [
    "hypercwd",
    "hyper-statusline",
    "hyper-electron-highlighter",
    "hyper-named-css-colors",
  ],
  localPlugins: [],
};
